INSERT INTO "control_points"(id, url, method) VALUES

(   1   ,   '/buildings'    ,   'GET'),
(   2   ,   '/buildings'    ,   'POST'),
(   3   ,   '/buildings/\\d' ,  'GET'),
(   4   ,   '/buildings/\\d' ,  'POST'),
(   5   ,   '/buildings/\\d' ,  'DELETE'),

(   6   ,   '/disciplines' ,        'GET'),
(   7   ,   '/disciplines' ,        'POST'),
(   8   ,   '/disciplines/\\d' ,    'GET'),
(   9   ,   '/disciplines/\\d' ,    'POST'),
(   10  ,   '/disciplines/\\d' ,    'DELETE'),

(   11  ,   '/lectureRooms' ,       'GET'),
(   12  ,   '/lectureRooms'    ,    'POST'),
(   13  ,   '/lectureRooms/\\d' ,   'GET'),
(   14  ,   '/lectureRooms/\\d' ,   'POST'),
(   15  ,   '/lectureRooms/\\d' ,   'DELETE'),

(   16  ,   '/lessonNumbers' ,   'GET'),
(   17  ,   '/lessonNumbers' ,   'POST'),
(   18  ,   '/lessonNumbers/\\d' ,  'GET'),
(   19  ,   '/lessonNumbers/\\d' ,  'POST'),
(   20  ,   '/lessonNumbers/\\d' ,  'DELETE'),

(   21  ,   '/lessonTypes' ,    'GET'),
(   22  ,   '/lessonTypes'    , 'POST'),
(   23  ,   '/lessonTypes/\\d' ,  'GET'),
(   24  ,   '/lessonTypes/\\d' ,  'POST'),
(   25  ,   '/lessonTypes/\\d' ,  'DELETE'),

(   26  ,   '/lessons' ,   'GET'),
(   27  ,   '/lessons' ,   'POST'),
(   28  ,   '/lessons/\\d' ,  'GET'),
(   29  ,   '/lessons/\\d' ,  'POST'),
(   30  ,   '/lessons/\\d' ,  'DELETE'),

(   31  ,   '/roomTypes' ,  'GET'),
(   32  ,   '/roomTypes'    ,   'POST'),
(   33  ,   '/roomTypes/\\d' ,  'GET'),
(   34  ,   '/roomTypes/\\d' ,  'POST'),
(   35  ,   '/roomTypes/\\d' ,  'DELETE'),

(   36  ,   '/departments' ,   'GET'),
(   37  ,   '/departments' ,   'POST'),
(   38  ,   '/departments/\\d' ,  'GET'),
(   39  ,   '/departments/\\d' ,  'POST'),
(   40  ,   '/departments/\\d' ,  'DELETE'),

(   41  ,   '/faculties' ,  'GET'),
(   42  ,   '/faculties'    ,   'POST'),
(   43  ,   '/faculties/\\d' ,  'GET'),
(   44  ,   '/faculties/\\d' ,  'POST'),
(   45  ,   '/faculties/\\d' ,  'DELETE'),

(   46  ,   '/groups' ,   'GET'),
(   47  ,   '/groups' ,   'POST'),
(   48  ,   '/groups/\\d' ,  'GET'),
(   49  ,   '/groups/\\d' ,  'POST'),
(   50  ,   '/groups/\\d' ,  'DELETE'),

(   51  ,   '/specialties' ,  'GET'),
(   52  ,   '/specialties'    ,   'POST'),
(   53  ,   '/specialties/\\d' ,  'GET'),
(   54  ,   '/specialties/\\d' ,  'POST'),
(   55  ,   '/specialties/\\d' ,  'DELETE'),

(   56  ,   '/departments' ,   'GET'),
(   57  ,   '/departments' ,   'POST'),
(   58  ,   '/departments/\\d' ,  'GET'),
(   59  ,   '/departments/\\d' ,  'POST'),
(   60  ,   '/departments/\\d' ,  'DELETE'),

(   61  ,   '/studyModes' ,  'GET'),
(   62  ,   '/studyModes'    ,   'POST'),
(   63  ,   '/studyModes/\\d' ,  'GET'),
(   64  ,   '/studyModes/\\d' ,  'POST'),
(   65  ,   '/studyModes/\\d' ,  'DELETE'),

(   66  ,   '/subgroups' ,   'GET'),
(   67  ,   '/subgroups' ,   'POST'),
(   68  ,   '/subgroups/\\d' ,  'GET'),
(   69  ,   '/subgroups/\\d' ,  'POST'),
(   70  ,   '/subgroups/\\d' ,  'DELETE'),

(   71  ,   '/graduationPapers' ,   'GET'),
(   72  ,   '/graduationPapers' ,   'POST'),
(   73  ,   '/graduationPapers/\\d' ,   'GET'),
(   74  ,   '/graduationPapers/\\d' ,   'POST'),
(   75  ,   '/graduationPapers/\\d' ,   'DELETE'),

(   76  ,   '/organizations'    ,   'GET'),
(   77  ,   '/organizations'    ,   'POST'),
(   78  ,   '/organizations/\\d',   'GET'),
(   79  ,   '/organizations/\\d',   'POST'),
(   80  ,   '/organizations/\\d',   'DELETE'),

(   81  ,   '/practices' ,  'GET'),
(   82  ,   '/practices'    ,   'POST'),
(   83  ,   '/practices/\\d' ,  'GET'),
(   84  ,   '/practices/\\d' ,  'POST'),
(   85  ,   '/practices/\\d' ,  'DELETE'),

(   86  ,   '/practiceTypes' ,   'GET'),
(   87  ,   '/practiceTypes' ,   'POST'),
(   88  ,   '/practiceTypes/\\d' ,  'GET'),
(   89  ,   '/practiceTypes/\\d' ,  'POST'),
(   90  ,   '/practiceTypes/\\d' ,  'DELETE'),

(   91  ,   '/requests' ,  'GET'),
(   92  ,   '/requests'    ,   'POST'),
(   93  ,   '/requests/\\d' ,  'GET'),
(   94  ,   '/requests/\\d' ,  'POST'),
(   95  ,   '/requests/\\d' ,  'DELETE'),

(   96  ,   '/resources' ,   'GET'),
(   97  ,   '/resources' ,   'POST'),
(   98  ,   '/resources/\\d' ,  'GET'),
(   99  ,   '/resources/\\d' ,  'POST'),
(  100  ,   '/resources/\\d' ,  'DELETE'),

(  101  ,   '/statuses' ,  'GET'),
(  102  ,   '/statuses'    ,   'POST'),
(  103  ,   '/statuses/\\d' ,  'GET'),
(  104  ,   '/statuses/\\d' ,  'POST'),
(  105  ,   '/statuses/\\d' ,  'DELETE'),

(  106  ,   '/termPapers' ,   'GET'),
(  107  ,   '/termPapers' ,   'POST'),
(  108  ,   '/termPapers/\\d' ,  'GET'),
(  109  ,   '/termPapers/\\d' ,  'POST'),
(  110  ,   '/termPapers/\\d' ,  'DELETE'),

(   111   ,   '/users'    ,   'GET'),
(   112   ,   '/users'    ,   'POST'),
(   113   ,   '/users/\\d' ,  'GET'),
(   114   ,   '/users/\\d' ,  'POST'),
(   115   ,   '/users/\\d' ,  'DELETE'),
(   116   ,   '/users/options', 'GET'),
(   117   ,   '/users/options', 'PUT'),

(   118   ,   '/roles' ,   'GET'),
(   119  ,   '/roles' ,   'POST'),
(   120  ,   '/roles/\\d' ,  'GET'),
(   121  ,   '/roles/\\d' ,  'POST'),
(   122  ,   '/roles/\\d' ,  'DELETE'),

(   123  ,   '/urls'    ,   'GET'),
(   124  ,   '/urls'    ,   'POST'),
(   125  ,   '/urls/\\d' ,  'GET'),
(   126  ,   '/urls/\\d' ,  'POST'),
(   127  ,   '/urls/\\d' ,  'DELETE'),

(   128  ,   '/teachers'    ,   'GET'),
(   129  ,   '/teachers'    ,   'POST'),
(   130  ,   '/teachers/\\d' ,  'GET'),
(   131  ,   '/teachers/\\d' ,  'POST'),
(   132  ,   '/teachers/\\d' ,  'DELETE'),

(   133  ,   '/students'    ,   'GET'),
(   134  ,   '/students'    ,   'POST'),
(   135  ,   '/students/\\d' ,  'GET'),
(   136  ,   '/students/\\d' ,  'POST'),
(   137  ,   '/students/\\d' ,  'DELETE');

INSERT INTO "roles_control_points"(role_id, control_point_id) VALUES

(   1   ,   1   ),
(   1   ,   2   ),
(   1   ,   3   ),
(   1   ,   4   ),
(   1   ,   5   ),

(   1   ,   6   ),
(   1   ,   7   ),
(   1   ,   8   ),
(   1   ,   9   ),
(   1   ,   10  ),

(   1   ,   11  ),
(   1   ,   12  ),
(   1   ,   13  ),
(   1   ,   14  ),
(   1   ,   15  ),

(   1   ,   16  ),
(   1   ,   17  ),
(   1   ,   18  ),
(   1   ,   19  ),
(   1   ,   20  ),

(   1   ,   21  ),
(   1   ,   22  ),
(   1   ,   23  ),
(   1   ,   24  ),
(   1   ,   25  ),

(   1   ,   26  ),
(   1   ,   27  ),
(   1   ,   28  ),
(   1   ,   29  ),
(   1   ,   30  ),

(   1   ,   31  ),
(   1   ,   32  ),
(   1   ,   33  ),
(   1   ,   34  ),
(   1   ,   35  ),

(   1   ,   36  ),
(   1   ,   37  ),
(   1   ,   38  ),
(   1   ,   39  ),
(   1   ,   40  ),

(   1   ,   41  ),
(   1   ,   42  ),
(   1   ,   43  ),
(   1   ,   44  ),
(   1   ,   45  ),

(   1   ,   46  ),
(   1   ,   47  ),
(   1   ,   48  ),
(   1   ,   49  ),
(   1   ,   50  ),

(   1   ,   51  ),
(   1   ,   52  ),
(   1   ,   53  ),
(   1   ,   54  ),
(   1   ,   55  ),

(   1   ,   56  ),
(   1   ,   57  ),
(   1   ,   58  ),
(   1   ,   59  ),
(   1   ,   60  ),

(   1   ,   61  ),
(   1   ,   62  ),
(   1   ,   63  ),
(   1   ,   64  ),
(   1   ,   65  ),

(   1   ,   66  ),
(   1   ,   67  ),
(   1   ,   68  ),
(   1   ,   69  ),
(   1   ,   70  ),

(   1   ,   71  ),
(   1   ,   72  ),
(   1   ,   73  ),
(   1   ,   74  ),
(   1   ,   75  ),

(   1   ,   76  ),
(   1   ,   77  ),
(   1   ,   78  ),
(   1   ,   79  ),
(   1   ,   80  ),

(   1   ,   81  ),
(   1   ,   82  ),
(   1   ,   83  ),
(   1   ,   84  ),
(   1   ,   85  ),

(   1   ,   86  ),
(   1   ,   87  ),
(   1   ,   88  ),
(   1   ,   89  ),
(   1   ,   90  ),

(   1   ,   91  ),
(   1   ,   92  ),
(   1   ,   93  ),
(   1   ,   94  ),
(   1   ,   95  ),

(   1   ,   96  ),
(   1   ,   97  ),
(   1   ,   98  ),
(   1   ,   99  ),
(   1   ,  100  ),

(   1   ,  101  ),
(   1   ,  102  ),
(   1   ,  103  ),
(   1   ,  104  ),
(   1   ,  105  ),

(   1   ,  106  ),
(   1   ,  107  ),
(   1   ,  108  ),
(   1   ,  109  ),
(   1   ,  110  ),

(   1   ,  111  ),
(   1   ,  112  ),
(   1   ,  113  ),
(   1   ,  114  ),
(   1   ,  115  ),
(   1   ,  116  ),
(   1   ,  117  ),
(   1   ,  118  ),

(   1   ,  119  ),
(   1   ,  120  ),
(   1   ,  121  ),
(   1   ,  122  ),
(   1   ,  123  ),

(   1   ,  124  ),
(   1   ,  125  ),
(   1   ,  126  ),
(   1   ,  127  ),
(   1   ,  128  ),

(   1   ,  129  ),
(   1   ,  130  ),
(   1   ,  131  ),
(   1   ,  132  ),
(   1   ,  133  ),

(   1   ,  134  ),
(   1   ,  135  ),
(   1   ,  136  ),
(   1   ,  137  );